export interface PlatformConfigs {
  adminRoles?: string[];
  cardBody?: boolean;
  remoteAnimation?: boolean;
  menuTransition?: boolean;
  remoteLayout?: boolean;
  layoutRadius?: number;
  layoutBlur?: number;
  remoteMenu?: boolean;
  storageEncode?: boolean;
  showBarSetting?: boolean;
  showBarNotice?: boolean;
  showBarSearch?: boolean;
  storageKey?: string;
  systemCode?: string;
  Version?: string;
  Title?: string;
  baseUrl?: string;
  FixedHeader?: boolean;
  HiddenSideBar?: boolean;
  MultiTagsCache?: boolean;
  MaxTagsLevel?: number;
  KeepAlive?: boolean;
  Locale?: string;
  Layout?: string;
  Theme?: string;
  DarkMode?: boolean;
  OverallStyle?: string;
  Grey?: boolean;
  Weak?: boolean;
  HideTabs?: boolean;
  HideFooter?: boolean;
  Stretch?: boolean | number;
  SidebarStatus?: boolean;
  EpThemeColor?: string;
  ShowLogo?: boolean;
  ShowModel?: string;
  MenuArrowIconNoTransition?: boolean;
  CachingAsyncRoutes?: boolean;
  TooltipEffect?: Effect;
  ResponsiveStorageNameSpace?: string;
  MenuSearchHistory?: number;
}
export type Effect = "light" | "dark";
