/**
 * 正则表达式工具常量
 */

// 示例正则表达式
export const REGEX_EXAMPLES = [
  {
    name: "邮箱验证",
    pattern: "^[\\w-]+(\\.[\\w-]+)*@[\\w-]+(\\.[\\w-]+)+$",
    flags: "g",
    testText: "test@example.com\ninvalid-email\nuser.name@company.co.uk",
    description: "匹配有效的电子邮件地址",
  },
  {
    name: "URL提取",
    pattern: "https?://[\\w-]+(\\.[\\w-]+)+(/[\\w-./?%&=]*)?",
    flags: "g",
    testText: "Visit our website at https://example.com/path?query=123\nOr http://another-site.org",
    description: "提取HTTP和HTTPS URL",
  },
  {
    name: "手机号码",
    pattern: "1[3-9]\\d{9}",
    flags: "g",
    testText: "联系电话：13812345678\n无效号码：12345678901\n另一个号码：18987654321",
    description: "匹配中国大陆手机号码",
  },
  {
    name: "HTML标签",
    pattern: "<([a-z]+)([^<]+)*(?:>(.*?)</\\1>|\\s*/>)",
    flags: "g",
    testText: '<div class="container">内容</div>\n<img src="image.jpg" />\n<p>段落<span>内联</span>文本</p>',
    description: "匹配HTML标签",
  },
  {
    name: "日期格式",
    pattern: "\\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])",
    flags: "g",
    testText: "日期：2023-01-15\n无效日期：2023-13-32\n另一个日期：2022-12-31",
    description: "匹配YYYY-MM-DD格式的日期",
  },
];

// 常用正则表达式
export const COMMON_PATTERNS = [
  { name: "邮箱", pattern: "^[\\w-]+(\\.[\\w-]+)*@[\\w-]+(\\.[\\w-]+)+$", description: "匹配有效的电子邮件地址" },
  { name: "URL", pattern: "https?://[\\w-]+(\\.[\\w-]+)+(/[\\w-./?%&=]*)?", description: "匹配HTTP和HTTPS URL" },
  { name: "手机号码", pattern: "1[3-9]\\d{9}", description: "匹配中国大陆手机号码" },
  { name: "身份证号", pattern: "(^\\d{15}$)|(^\\d{18}$)|(^\\d{17}(\\d|X|x)$)", description: "匹配15位或18位身份证号" },
  { name: "IP地址", pattern: "((2(5[0-5]|[0-4]\\d))|[0-1]?\\d{1,2})(\\.((2(5[0-5]|[0-4]\\d))|[0-1]?\\d{1,2})){3}", description: "匹配IPv4地址" },
  { name: "日期(YYYY-MM-DD)", pattern: "\\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])", description: "匹配YYYY-MM-DD格式的日期" },
  { name: "时间(HH:MM:SS)", pattern: "([01]\\d|2[0-3]):([0-5]\\d):([0-5]\\d)", description: "匹配24小时制时间" },
  { name: "HTML标签", pattern: "<([a-z]+)([^<]+)*(?:>(.*?)</\\1>|\\s*/>)", description: "匹配HTML标签" },
  { name: "中文字符", pattern: "[\\u4e00-\\u9fa5]", description: "匹配中文字符" },
  { name: "双字节字符", pattern: "[^\\x00-\\xff]", description: "匹配双字节字符(包括中文)" },
  { name: "正整数", pattern: "^[1-9]\\d*$", description: "匹配正整数" },
  { name: "负整数", pattern: "^-[1-9]\\d*$", description: "匹配负整数" },
  { name: "整数", pattern: "^-?[1-9]\\d*$", description: "匹配整数" },
  { name: "浮点数", pattern: "^-?([1-9]\\d*\\.\\d*|0\\.\\d*[1-9]\\d*|0?\\.0+|0)$", description: "匹配浮点数" },
  { name: "QQ号", pattern: "[1-9][0-9]{4,}", description: "匹配QQ号(5位以上数字)" },
  { name: "邮政编码", pattern: "[1-9]\\d{5}(?!\\d)", description: "匹配中国邮政编码" },
  { name: "密码强度", pattern: "^(?=.*\\d)(?=.*[a-z])(?=.*[A-Z]).{8,}$", description: "至少8位，包含大小写字母和数字" },
  { name: "16进制颜色", pattern: "#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})", description: "匹配CSS中的16进制颜色值" },
  { name: "IPv6地址", pattern: "(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))", description: "匹配IPv6地址" },
  { name: "MAC地址", pattern: "([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})", description: "匹配MAC地址" },
  { name: "XML标签", pattern: "<\\/?[\\w\\s=\"\\.\\-\\:]+(\\/)?\\s*>", description: "匹配XML标签" },
  { name: "JSON属性", pattern: "\"([^\"]+)\"\\s*:\\s*(\"[^\"]*\"|\\d+|true|false|null|\\{[^}]*\\}|\\[[^\\]]*\\])", description: "匹配JSON属性" },
  { name: "用户名", pattern: "^[a-zA-Z][a-zA-Z0-9_]{3,15}$", description: "字母开头，允许4-16字节，字母数字下划线" },
  { name: "域名", pattern: "([a-zA-Z0-9]([a-zA-Z0-9\\-]{0,61}[a-zA-Z0-9])?\\.)+[a-zA-Z]{2,6}", description: "匹配域名" },
  { name: "车牌号", pattern: "[京津沪渝冀豫云辽黑湘皖鲁新苏浙赣鄂桂甘晋蒙陕吉闽贵粤青藏川宁琼使领][A-Z][A-HJ-NP-Z0-9]{4,5}[A-HJ-NP-Z0-9挂学警港澳]", description: "匹配中国车牌号" },
  { name: "银行卡号", pattern: "\\d{13,19}", description: "匹配银行卡号(13-19位数字)" },
  { name: "护照号码", pattern: "[A-Z]{1,2}\\d{6,10}([A-Z])?", description: "匹配护照号码" },
  { name: "图片文件名", pattern: "([^\\s]+(\\.(?i)(jpg|jpeg|png|gif|bmp))$)", description: "匹配图片文件名" },
  { name: "视频文件名", pattern: "([^\\s]+(\\.(?i)(avi|mp4|mov|wmv|flv|mkv))$)", description: "匹配视频文件名" },
  { name: "文档文件名", pattern: "([^\\s]+(\\.(?i)(doc|docx|pdf|xls|xlsx|ppt|pptx))$)", description: "匹配文档文件名" },
  { name: "CSS属性", pattern: "[a-z\\-]+\\s*:\\s*[^;]+;", description: "匹配CSS属性" },
  { name: "JS变量声明", pattern: "(var|let|const)\\s+[a-zA-Z_$][0-9a-zA-Z_$]*\\s*=?", description: "匹配JavaScript变量声明" },
  { name: "HTML注释", pattern: "<!--[\\s\\S]*?-->", description: "匹配HTML注释" },
  { name: "JS注释", pattern: "(\\/\\/.*|\\/\\*[\\s\\S]*?\\*\\/)", description: "匹配JavaScript注释" },
  { name: "CSS注释", pattern: "\\/\\*[\\s\\S]*?\\*\\/", description: "匹配CSS注释" },
  { name: "HTTP链接", pattern: "(https?:\\/\\/)?([\\da-z\\.-]+)\\.([a-z\\.]{2,6})([\\/\\w \\.-]*)*\\/?", description: "匹配HTTP链接" },
  { name: "FTP链接", pattern: "ftp:\\/\\/[\\w-]+(\\.[\\w-]+)+([\\w-.,@?^=%&:/~+#]*[\\w-@?^=%&/~+#])?", description: "匹配FTP链接" },
  { name: "年龄", pattern: "^(?:[1-9][0-9]?|1[01][0-9]|120)$", description: "匹配0-120岁的年龄" },
  { name: "经度", pattern: "^[-+]?(180(\\.0+)?|((1[0-7]\\d)|([1-9]?\\d))(\\.\\d+)?)$", description: "匹配经度(-180到180)" },
  { name: "纬度", pattern: "^[-+]?([0-8]?\\d(\\.\\d+)?|90(\\.0+)?)$", description: "匹配纬度(-90到90)" },
  { name: "GUID/UUID", pattern: "[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}", description: "匹配GUID/UUID" },
  { name: "Base64", pattern: "^[A-Za-z0-9+/]{4}*([A-Za-z0-9+/]{4}|[A-Za-z0-9+/]{3}=|[A-Za-z0-9+/]{2}==)$", description: "匹配Base64编码" },
  { name: "ISBN-10", pattern: "^(?:ISBN(?:-10)?:? )?(?=[0-9X]{10}$|(?=(?:[0-9]+[- ]){3})[- 0-9X]{13}$)[0-9]{1,5}[- ]?[0-9]+[- ]?[0-9]+[- ]?[0-9X]$", description: "匹配ISBN-10" },
  { name: "ISBN-13", pattern: "^(?:ISBN(?:-13)?:? )?(?=[0-9]{13}$|(?=(?:[0-9]+[- ]){4})[- 0-9]{17}$)97[89][- ]?[0-9]{1,5}[- ]?[0-9]+[- ]?[0-9]+[- ]?[0-9]$", description: "匹配ISBN-13" },
  { name: "信用卡号", pattern: "^(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|6(?:011|5[0-9][0-9])[0-9]{12}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|(?:2131|1800|35\\d{3})\\d{11})$", description: "匹配信用卡号" },
  { name: "中文姓名", pattern: "^[\\u4e00-\\u9fa5]{2,4}$", description: "匹配2-4个汉字的中文姓名" },
  { name: "英文姓名", pattern: "^[a-zA-Z]+(([',. -][a-zA-Z ])?[a-zA-Z]*)*$", description: "匹配英文姓名" },
  { name: "文件路径", pattern: "^(\\/[^/ ]*)+\\/?$", description: "匹配Unix文件路径" },
  { name: "Windows路径", pattern: "^[a-zA-Z]:\\\\(?:[^\\\\/:*?\"<>|\\r\\n]+\\\\)*[^\\\\/:*?\"<>|\\r\\n]*$", description: "匹配Windows文件路径" },
  { name: "URL参数", pattern: "[?&][^=&]+=([^&]*)", description: "匹配URL参数" },
  { name: "Twitter用户名", pattern: "@([A-Za-z0-9_]{1,15})", description: "匹配Twitter用户名" },
  { name: "YouTube链接", pattern: "^((?:https?:)?\\/\\/)?((?:www|m)\\.)?((?:youtube\\.com|youtu.be))(\\/(?:[\\w\\-]+\\?v=|embed\\/|v\\/)?)([\\w\\-]+)(\\S+)?$", description: "匹配YouTube链接" },
  { name: "微信号", pattern: "^[a-zA-Z][-_a-zA-Z0-9]{5,19}$", description: "匹配微信号" },
  { name: "固定电话", pattern: "\\d{3}-\\d{8}|\\d{4}-\\d{7}", description: "匹配固定电话号码" },
  { name: "统一社会信用代码", pattern: "[0-9A-HJ-NPQRTUWXY]{2}\\d{6}[0-9A-HJ-NPQRTUWXY]{10}", description: "匹配统一社会信用代码" },
  { name: "HTML实体", pattern: "&[a-zA-Z][a-zA-Z0-9]*;|&#[0-9]+;|&#x[0-9a-fA-F]+;", description: "匹配HTML实体" },
  { name: "SQL语句", pattern: "(SELECT|INSERT|UPDATE|DELETE|CREATE|ALTER|DROP)\\s+.*", description: "匹配SQL语句" },
  { name: "版本号", pattern: "^\\d+\\.\\d+\\.\\d+(-[a-zA-Z0-9]+)?$", description: "匹配语义化版本号" },
  { name: "中国邮箱", pattern: "[a-zA-Z0-9_-]+@(163|126|qq|sina|sohu|yahoo|hotmail|gmail|outlook)(\\.com|\\.cn)", description: "匹配常见中国邮箱" },
  { name: "IPv4段", pattern: "((2(5[0-5]|[0-4]\\d))|[0-1]?\\d{1,2})(\\.((2(5[0-5]|[0-4]\\d))|[0-1]?\\d{1,2})){3}\\/([1-9]|[1-2]\\d|3[0-2])", description: "匹配IPv4网段(CIDR)" },
  { name: "JS函数声明", pattern: "function\\s+([a-zA-Z_$][0-9a-zA-Z_$]*)\\s*\\([^)]*\\)\\s*\\{", description: "匹配JS函数声明" },
  { name: "CSS选择器", pattern: "[.#]?[a-zA-Z][a-zA-Z0-9_-]*(?:\\[[^\\]]+\\]|:[a-zA-Z0-9_-]+)*", description: "匹配CSS选择器" },
  { name: "HTML属性", pattern: "\\s[a-zA-Z-]+=\"[^\"]*\"", description: "匹配HTML属性" },
  { name: "JS箭头函数", pattern: "\\([^)]*\\)\\s*=>\\s*\\{[^}]*\\}", description: "匹配JS箭头函数" },
  { name: "JS Promise链", pattern: "\\.then\\(.*\\)\\.catch\\(.*\\)", description: "匹配JS Promise链" },
  { name: "CSS媒体查询", pattern: "@media\\s+[^{]+\\{[^}]*\\}", description: "匹配CSS媒体查询" },
  { name: "HTML5标签", pattern: "<(article|aside|audio|canvas|command|datalist|details|embed|figcaption|figure|footer|header|hgroup|keygen|mark|meter|nav|output|progress|rp|rt|ruby|section|source|summary|time|video)[^>]*>", description: "匹配HTML5特有标签" },
  { name: "JS模板字符串", pattern: "`[^`]*`", description: "匹配JS模板字符串" },
  { name: "CSS变量", pattern: "var\\(--[a-zA-Z0-9-_]+\\)", description: "匹配CSS变量" },
  { name: "JS解构赋值", pattern: "const\\s+\\{[^}]+\\}\\s*=\\s*[^;]+", description: "匹配JS解构赋值" },
  { name: "Vue指令", pattern: "v-[a-z]+(?::[a-z]+)?(?:\\.([a-z]+))*", description: "匹配Vue指令" },
  { name: "React组件", pattern: "<[A-Z][a-zA-Z]*[^>]*\\/?>", description: "匹配React组件" },
  { name: "JS导入语句", pattern: "import\\s+(?:\\{[^}]+\\}\\s+from\\s+)?['\"][^'\"]+['\"]", description: "匹配JS导入语句" },
  { name: "JS导出语句", pattern: "export\\s+(?:default\\s+)?(?:const|let|var|function|class)\\s+[a-zA-Z_$][0-9a-zA-Z_$]*", description: "匹配JS导出语句" },
  { name: "JS类声明", pattern: "class\\s+[a-zA-Z_$][0-9a-zA-Z_$]*(?:\\s+extends\\s+[a-zA-Z_$][0-9a-zA-Z_$]*)?\\s*\\{", description: "匹配JS类声明" },
  { name: "JS异步函数", pattern: "async\\s+function\\s+[a-zA-Z_$][0-9a-zA-Z_$]*\\s*\\([^)]*\\)\\s*\\{", description: "匹配JS异步函数" },
  { name: "JS生成器函数", pattern: "function\\s*\\*\\s+[a-zA-Z_$][0-9a-zA-Z_$]*\\s*\\([^)]*\\)\\s*\\{", description: "匹配JS生成器函数" },
  { name: "JS try-catch", pattern: "try\\s*\\{[^}]*\\}\\s*catch\\s*\\([^)]*\\)\\s*\\{[^}]*\\}", description: "匹配JS try-catch语句" },
  { name: "JS switch语句", pattern: "switch\\s*\\([^)]*\\)\\s*\\{[^}]*\\}", description: "匹配JS switch语句" },
  { name: "JS for循环", pattern: "for\\s*\\([^)]*\\)\\s*\\{[^}]*\\}", description: "匹配JS for循环" },
  { name: "JS while循环", pattern: "while\\s*\\([^)]*\\)\\s*\\{[^}]*\\}", description: "匹配JS while循环" },
  { name: "JS if语句", pattern: "if\\s*\\([^)]*\\)\\s*\\{[^}]*\\}", description: "匹配JS if语句" },
  { name: "JS else语句", pattern: "else\\s*\\{[^}]*\\}", description: "匹配JS else语句" },
  { name: "JS三元运算符", pattern: "[^?]+\\?[^:]+:[^;]+", description: "匹配JS三元运算符" },
  { name: "JS正则表达式", pattern: "\\/[^/]+\\/[gimsuy]*", description: "匹配JS正则表达式字面量" },
  { name: "JS对象字面量", pattern: "\\{\\s*[a-zA-Z_$][0-9a-zA-Z_$]*\\s*:\\s*[^,}]+(?:,\\s*[a-zA-Z_$][0-9a-zA-Z_$]*\\s*:\\s*[^,}]+)*\\s*\\}", description: "匹配JS对象字面量" },
  { name: "JS数组字面量", pattern: "\\[\\s*[^\\[\\]]*\\s*\\]", description: "匹配JS数组字面量" },
  { name: "JS字符串字面量", pattern: "(['\"])[^\\1]*?\\1", description: "匹配JS字符串字面量" },
];

// 正则表达式语法帮助
export const REGEX_HELP = {
  character: [
    { symbol: ".", description: "匹配除换行符外的任意字符" },
    { symbol: "\\w", description: "匹配字母、数字、下划线" },
    { symbol: "\\d", description: "匹配数字" },
    { symbol: "\\s", description: "匹配空白字符" },
    { symbol: "\\W", description: "匹配非字母、数字、下划线" },
    { symbol: "\\D", description: "匹配非数字" },
    { symbol: "\\S", description: "匹配非空白字符" },
    { symbol: "[abc]", description: "匹配方括号内的任意字符" },
    { symbol: "[^abc]", description: "匹配除方括号内的任意字符" },
    { symbol: "[a-z]", description: "匹配a到z的任意字符" },
  ],
  anchor: [
    { symbol: "^", description: "匹配字符串开头" },
    { symbol: "$", description: "匹配字符串结尾" },
    { symbol: "\\b", description: "匹配单词边界" },
    { symbol: "\\B", description: "匹配非单词边界" },
  ],
  quantifier: [
    { symbol: "*", description: "匹配前面的子表达式零次或多次" },
    { symbol: "+", description: "匹配前面的子表达式一次或多次" },
    { symbol: "?", description: "匹配前面的子表达式零次或一次" },
    { symbol: "{n}", description: "匹配前面的子表达式恰好n次" },
    { symbol: "{n,}", description: "匹配前面的子表达式至少n次" },
    { symbol: "{n,m}", description: "匹配前面的子表达式n到m次" },
  ],
  group: [
    { symbol: "(xyz)", description: "捕获组，匹配并记住匹配的字符串" },
    { symbol: "(?:xyz)", description: "非捕获组，匹配但不记住匹配的字符串" },
    { symbol: "(?=xyz)", description: "正向肯定预查，匹配xyz前面的位置" },
    { symbol: "(?!xyz)", description: "正向否定预查，匹配后面不是xyz的位置" },
    { symbol: "(?<=xyz)", description: "反向肯定预查，匹配xyz后面的位置" },
    { symbol: "(?<!xyz)", description: "反向否定预查，匹配前面不是xyz的位置" },
  ],
  flag: [
    { symbol: "g", description: "全局匹配" },
    { symbol: "i", description: "忽略大小写" },
    { symbol: "m", description: "多行匹配" },
    { symbol: "s", description: "允许.匹配换行符" },
    { symbol: "u", description: "使用unicode码的模式" },
    { symbol: "y", description: "粘性匹配" },
  ],
};