[package]
name = "codec_wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
getrandom = { version = "0.2", features = ["js"] }
hex = "0.4"
md-5 = "0.10"
sm3 = "0.4"
sm4 = "0.4"
sm2 = "0.13.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
js-sys = "0.3"
base64 = "0.21"
# 添加AES加密库依赖
aes = "0.8"
cbc = "0.1"
block-padding = "0.3"
# 添加wasm-bindgen依赖
wasm-bindgen = "0.2"
# 添加smcrypto库用于SM2加密解密
smcrypto = "0.3.1"

[dependencies.web-sys]
version = "0.3"
features = [
  "console",
]