[package]
name = "codec_wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
getrandom = { version = "0.2", features = ["js"] }
hex = "0.4"
md-5 = "0.10"
sm3 = "0.4"
sm4 = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
js-sys = "0.3"
# 使用标准的加密库
aes = "0.8"
cbc = "0.1"
block-padding = "0.3"
base64 = "0.21"
generic-array = "0.14"

# 为了解决版本冲突，明确指定cipher版本
cipher = "0.4"

[dependencies.web-sys]
version = "0.3"
features = [
  "console",
]