Title: 系统管理
showBarSetting: true
openAuth: true
remoteMenu: true
remoteLayout: true
baseUrl: /tenant/api
# AccountType: tenant
OpenTenantLogin: true
OpenTenantBase: true
OpenShowRefreshToken: true
OpenSettingEmail: true
OpenSettingSms: true
OpenSettingLlm: true
storageEncode: false
