-- 学校信息表
CREATE TABLE `school_info` (
  `school_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '学校ID',
  `school_name` varchar(100) NOT NULL COMMENT '学校名称',
  `school_code` varchar(50) DEFAULT NULL COMMENT '学校代码',
  `school_type` varchar(20) DEFAULT NULL COMMENT '学校类型(小学/初中/高中/大学)',
  `school_level` varchar(20) DEFAULT NULL COMMENT '学校等级(省重点/市重点/普通)',
  `school_address` varchar(200) DEFAULT NULL COMMENT '学校地址',
  `school_province` varchar(50) DEFAULT NULL COMMENT '所在省份',
  `school_city` varchar(50) DEFAULT NULL COMMENT '所在城市',
  `school_district` varchar(50) DEFAULT NULL COMMENT '所在区县',
  `school_phone` varchar(20) DEFAULT NULL COMMENT '联系电话',
  `school_email` varchar(100) DEFAULT NULL COMMENT '电子邮箱',
  `school_website` varchar(100) DEFAULT NULL COMMENT '学校网站',
  `school_founding_date` date DEFAULT NULL COMMENT '建校日期',
  `school_area` decimal(10,2) DEFAULT NULL COMMENT '占地面积(平方米)',
  `school_building_area` decimal(10,2) DEFAULT NULL COMMENT '建筑面积(平方米)',
  `school_student_count` int(11) DEFAULT NULL COMMENT '学生总数',
  `school_teacher_count` int(11) DEFAULT NULL COMMENT '教师总数',
  `school_class_count` int(11) DEFAULT NULL COMMENT '班级总数',
  `school_description` text DEFAULT NULL COMMENT '学校简介',
  `school_features` varchar(500) DEFAULT NULL COMMENT '学校特色',
  `school_principal` varchar(50) DEFAULT NULL COMMENT '校长姓名',
  `school_logo` varchar(255) DEFAULT NULL COMMENT '学校logo地址',
  `school_status` tinyint(1) DEFAULT 1 COMMENT '状态(0停用,1正常)',
  `school_create_by` varchar(64) DEFAULT '' COMMENT '创建者',
  `school_create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `school_update_by` varchar(64) DEFAULT '' COMMENT '更新者',
  `school_update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `school_remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `school_deleted` tinyint(1) DEFAULT 0 COMMENT '删除标志(0存在,1删除)',
  PRIMARY KEY (`school_id`),
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='学校信息表';