-- 学校招生计划表
CREATE TABLE `school_enrollment_plan` (
  `school_plan_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '计划ID',
  `school_id` bigint(20) NOT NULL COMMENT '学校ID',
  `school_plan_year` int(4) NOT NULL COMMENT '招生年份',
  `school_plan_name` varchar(100) NOT NULL COMMENT '计划名称',
  `school_plan_code` varchar(50) DEFAULT NULL COMMENT '计划编号',
  `school_plan_type` varchar(30) DEFAULT NULL COMMENT '计划类型(统招/自主招生/特长生等)',
  `school_plan_level` varchar(20) DEFAULT NULL COMMENT '招生层次(小学/初中/高中/本科/研究生等)',
  `school_plan_major` varchar(100) DEFAULT NULL COMMENT '招生专业',
  `school_plan_subject_id` bigint(20) DEFAULT NULL COMMENT '关联学科ID',
  `school_plan_quota` int(11) DEFAULT NULL COMMENT '招生名额',
  `school_plan_enrolled` int(11) DEFAULT 0 COMMENT '已录取人数',
  `school_plan_min_score` decimal(10,2) DEFAULT NULL COMMENT '最低录取分数',
  `school_plan_avg_score` decimal(10,2) DEFAULT NULL COMMENT '平均录取分数',
  `school_plan_start_date` date DEFAULT NULL COMMENT '招生开始日期',
  `school_plan_end_date` date DEFAULT NULL COMMENT '招生结束日期',
  `school_plan_exam_date` date DEFAULT NULL COMMENT '考试日期',
  `school_plan_result_date` date DEFAULT NULL COMMENT '录取结果公布日期',
  `school_plan_fee` decimal(10,2) DEFAULT NULL COMMENT '学费标准(元/年)',
  `school_plan_scholarship` text DEFAULT NULL COMMENT '奖学金政策',
  `school_plan_requirement` text DEFAULT NULL COMMENT '报名要求',
  `school_plan_process` text DEFAULT NULL COMMENT '招生流程',
  `school_plan_contact` varchar(50) DEFAULT NULL COMMENT '联系人',
  `school_plan_phone` varchar(20) DEFAULT NULL COMMENT '联系电话',
  `school_plan_email` varchar(100) DEFAULT NULL COMMENT '联系邮箱',
  `school_plan_website` varchar(255) DEFAULT NULL COMMENT '招生网站',
  `school_plan_attachment` varchar(255) DEFAULT NULL COMMENT '附件路径',
  `school_plan_province` varchar(50) DEFAULT NULL COMMENT '招生省份',
  `school_plan_city` varchar(50) DEFAULT NULL COMMENT '招生城市',
  `school_plan_district` varchar(50) DEFAULT NULL COMMENT '招生区县',
  `school_plan_priority` int(11) DEFAULT 0 COMMENT '优先级',
  `school_plan_status` tinyint(1) DEFAULT 1 COMMENT '状态(0关闭,1进行中,2已结束)',
  `school_plan_description` text DEFAULT NULL COMMENT '计划描述',
  `school_plan_create_by` varchar(64) DEFAULT '' COMMENT '创建者',
  `school_plan_create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `school_plan_update_by` varchar(64) DEFAULT '' COMMENT '更新者',
  `school_plan_update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `school_plan_remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `school_plan_deleted` tinyint(1) DEFAULT 0 COMMENT '删除标志(0存在,1删除)',
  PRIMARY KEY (`school_plan_id`),
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='学校招生计划表';