-- 学校学科表
CREATE TABLE `school_subject` (
  `school_subject_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '学科ID',
  `school_id` bigint(20) NOT NULL COMMENT '所属学校ID',
  `school_subject_name` varchar(100) NOT NULL COMMENT '学科名称',
  `school_subject_code` varchar(50) DEFAULT NULL COMMENT '学科代码',
  `school_subject_type` varchar(20) DEFAULT NULL COMMENT '学科类型(必修/选修)',
  `school_subject_category` varchar(50) DEFAULT NULL COMMENT '学科分类(文科/理科/艺术/体育等)',
  `school_subject_credit` decimal(5,2) DEFAULT NULL COMMENT '学科学分',
  `school_subject_hours` int(11) DEFAULT NULL COMMENT '课时数',
  `school_subject_description` text DEFAULT NULL COMMENT '学科描述',
  `school_subject_requirement` text DEFAULT NULL COMMENT '学科要求',
  `school_subject_grade` varchar(20) DEFAULT NULL COMMENT '适用年级',
  `school_subject_semester` varchar(20) DEFAULT NULL COMMENT '适用学期(上学期/下学期/全年)',
  `school_subject_teacher_count` int(11) DEFAULT NULL COMMENT '任课教师数量',
  `school_subject_student_count` int(11) DEFAULT NULL COMMENT '选课学生数量',
  `school_subject_textbook` varchar(200) DEFAULT NULL COMMENT '使用教材',
  `school_subject_is_main` tinyint(1) DEFAULT 0 COMMENT '是否主科(0否,1是)',
  `school_subject_is_exam` tinyint(1) DEFAULT 0 COMMENT '是否考试科目(0否,1是)',
  `school_subject_exam_type` varchar(50) DEFAULT NULL COMMENT '考试类型(笔试/口试/实验等)',
  `school_subject_order` int(11) DEFAULT 0 COMMENT '显示顺序',
  `school_subject_status` tinyint(1) DEFAULT 1 COMMENT '状态(0停用,1正常)',
  `school_subject_create_by` varchar(64) DEFAULT '' COMMENT '创建者',
  `school_subject_create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `school_subject_update_by` varchar(64) DEFAULT '' COMMENT '更新者',
  `school_subject_update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `school_subject_remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `school_subject_deleted` tinyint(1) DEFAULT 0 COMMENT '删除标志(0存在,1删除)',
  PRIMARY KEY (`school_subject_id`),
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='学校学科表';